[versions]
accompanist-navigation-animation = "0.25.1"
accompanist-permissions = "0.17.0"
accompanist-swiperefresh = "0.13.0"
activity-compose = "1.6.0"
androidx-junit = "1.1.5"
appcompat = "1.6.1"
core-ktx = "1.9.0"
desugar_jdk_libs = "1.2.2"
espresso = "3.5.1"
junit = "4.13.2"
kotlin = '1.7.20'
compose = '1.3.1'
coroutines = "1.6.4"
lifecycle = "2.5.1"
material = "1.8.0"
multidex = "2.0.1"
okio = "3.2.0"
retrofit = '2.9.0'
okhttp = '4.9.0'
moshi = '1.13.0'
room = '2.5.0'
hilt = '2.44'
workmanager = '2.7.1'
agp = "8.2.0"

[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-legacy = "androidx.legacy:legacy-support-v4:1.0.0"
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "workmanager" }

compose-materialIcons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
compose-materialIcons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-constraintLayout = "androidx.constraintlayout:constraintlayout-compose:1.0.0"

navigation-compose = "androidx.navigation:navigation-compose:2.5.1"

accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist-navigation-animation" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist-swiperefresh" }

desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }

kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-metadata-jvm = "org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.5.0"

hilt-gradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-androidCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-compiler = "com.google.dagger:hilt-compiler:1.0.0"
hilt-navigationCompose = "androidx.hilt:hilt-navigation-compose:1.0.0"
hilt-work = "androidx.hilt:hilt-work:1.0.0"

material = { module = "com.google.android.material:material", version.ref = "material" }

okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
moshi-core = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

timber = "com.jakewharton.timber:timber:4.7.1"

espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]